# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.BigIntegerField()),
                ('ctime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='table',
            name='u0',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='table_u0', to='web.User'),
        ),
        migrations.AddField(
            model_name='table',
            name='u1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='table_u1', to='web.User'),
        ),
        migrations.AddField(
            model_name='log',
            name='u0',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='log_u0', to='web.User'),
        ),
        migrations.AddField(
            model_name='log',
            name='u1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='log_u1', to='web.User'),
        ),
    ]
