# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='val',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='table',
            name='val',
            field=models.BigIntegerField(default=0),
        ),
    ]
