# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20170106_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='comment',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
